# このワークフローは、新しいコンテナイメージを構築し、Amazon ECR에 푸시합니다.
# 然后，如果要推到“主”分支，则将新的任务定义部署到Amazon ECS.
#
#  要使用此工作流，您必须完成以下设置步骤:
#
#  1.创建用于保存图像的存储库 。
# AWS ECR 창고를 작성합니다. -- 리포지토리 이름 MyEcleRepo --  美国东部地区-2 。
#  将以下工作流环境变量的值替换为存储库名称：
# 将以下工作流环境变量"自动气象站区域"的值替换为存储库区域。
#
#  2.创建任务定义、群集和服务。
# 예를 들어, ECS 콘솔의 시작 지침을 따르십시오.
# https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2 #  /第一次运行
# 将以下工作流环境变量_服务“的值替换为您为亚马逊服务设置的名称。
#  将以下工作流的环境变量的值替换为群集的名称。
#
# 3. 작업 정의를 저장소에 json 파일로 저장합니다.
#  格式应遵循注册任务定义的输出。  --  生成器骨架。
#  将以下工作流环境变量的值替换为文件的路径。
#  将以下工作流环境变量"容器名称"的值替换为容器名称:
#  在任务定义的容器定义部分中。
#
# 4.GitHub操作系统超级英雄ユーザーアクセスキーを`AWS_ACCESS_KEY_ID`と`AWS_SECRET_ACCESS_KEY`に格纳します。
# 有关此iam用户的建议iam策略，请参阅以下每个操作的文档：
#  以及处理访问密钥凭据的最佳实践 。

7名称:在亚马逊上部署

二:
推压，推压:
分支机构:[分支机构:[ "主要的:[“主要的"주제" ]

环境:
区域自动气象站: 我的区域#将此设置为您首选的AWS区域，例如美国西部-1。
ECR_存储库: 我的_ECR_存储库#将此设置为您的Amazon ECR存储库名称
ECS_服务: 我的_ECS_服务#将此设置为您的Amazon ECS服务名称
ECS_集群: 我的_ECS_集群#将此设置为您的Amazon ECS群集名称
ECS_任务_定义: 我的_ECS_任务_定义#将此设置为Amazon ECS任务定义的路径
                                               #文件，例如/任务定义.json
容器名称: 我的_容器_名称#将其设置为容器的名称
                                               #任务定义的containerDefinitions节

权限:
目录: 阅读

工作:
部署:
姓名: 部署
奔跑: Ubuntu最新
环境: 生产

步骤:
    - 姓名: 结账
用途: 操作/签出@v3

    - 姓名: 配置AWS凭据
用途: AWS-操作/配置-AWS-凭据@v1
和:
访问键ID: ${{密码.AWS_ACCESS_KEY_ID}}
密码访问键: ${{机密.AWS_Secret_ACCESS_KEY}}
区域: ${{区域导航}}

-명:아마존 ECR에 로그인
身份证件:洛金电子
용도: 사용자 이름: 로그인 @v1

- 이름:이미지를 Amazon ecr에 구축,태그 및 푸시
身份证件:建立映像
环境:
ECR_ 레지스트리:${{steps.login-ecr.outputs.registry}}
图像标签:${{吉托沙}}
运行:|
# Docker 컨테이너를 구축하고
# ECR에 밀어넣기
# ECS에 배포되었습니다.
ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG
ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG
返回“image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG”>>$GITHUB_OUTPUT

이름: Amazon ECS 작업 정의에 새 이미지 ID 입력
身份证件:任务确定
사용법:아워스 액션/아마존- ecs - 렌더링 작업 정의 @v1
和:
任务定义:${{에이. ECS_TASK_DEFINITION (주) (주)}}
容器名称:${{附件_姓名}}
图像:${{steps.build-image.outputs.image}}

-명:Amazon ECS 작업 정의 배포
用途:AWS-actions/amazon-ecs-部署-任务定义@v1
和:
任务定义:${{步骤、任务定义、输出、任务定义}}
服务:${{엔v. ECS_서비스}}
簇:${{엔v. ECS_클러스터 시스템}}
wait-for-service-stability:真实的
